doubans/urls.py
from django.conf.urls import url,include
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('haystack.urls')),
    url(r'^',include('myapp.urls',namespace='myapp')),
    url(r'^captcha/', include('captcha.urls')),


]

myapp/urls.py
from django.conf.urls import url

from . import views




urlpatterns = [
    url(r'^start/$', views.start, name="start"),
    url(r'^base/$', views.base, name="base"),
    url(r'^home/$',views.home,name="home"),
    url(r'^tuijian/$', views.tuijian, name="tuijian"),
    url(r'^tuijian/(\d+)/$',views.tuijian,name="tuijian"),
    url(r'^mine/$',views.mine,name="mine"),
    url(r'^mine/(\d+)/$',views.mine,name="mine"),
    url(r'^lianxi/$',views.lianxi,name="lianxi"),
    url(r'^like/$',views.like,name="like"),
    url(r'^like/(\d+)/$',views.like,name="like"),
    url(r'^login/$',views.login1,name="login"),
    url(r'^register/$',views.register,name="register"),
    url(r'^loginout/$',views.loginout,name="loginout"),
    url(r'^user_center/$',views.user_center,name="user_center"),
    url(r'^user_center/edit_profile/$', views.edit_profile, name="edit_profile"),
    url(r'^user_center/change_password/$', views.change_password, name="change_password"),










]

myapp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class DjangoMigrations(models.Model):
   app = models.CharField(max_length=255)
   name = models.CharField(max_length=255)
   applied = models.DateTimeField()

class Meta:
       managed = False
       db_table = 'django_migrations'


class Doubans(models.Model):


    name = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    company = models.CharField(max_length=255, blank=True, null=True)
    score = models.CharField(max_length=255, blank=True, null=True)
    summary = models.CharField(max_length=255, blank=True, null=True)
    price = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'doubans'


class Ordinarymember(models.Model):

     用户 = models.OneToOneField(User,on_delete=models.CASCADE)
     昵称 = models.CharField(max_length=50,blank=True)
     生日 = models.CharField(max_length=50,blank=True,null=True)

     class Meta:
         verbose_name_plural = "ordinarymembers"

class Biancheng(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=50, blank=True, null=True)
    company = models.CharField(max_length=50, blank=True, null=True)
    score = models.CharField(max_length=50, blank=True, null=True)
    summary = models.CharField(max_length=255, blank=True, null=True)
    price = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'biancheng'


class Keji(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=50, blank=True, null=True)
    company = models.CharField(max_length=50, blank=True, null=True)
    score = models.CharField(max_length=50, blank=True, null=True)
    summary = models.CharField(max_length=255, blank=True, null=True)
    price = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'keji'


myapp/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from captcha.fields import CaptchaField
class Custom_Table(UserCreationForm):
    昵称 = forms.CharField(max_length=50,required=False)
    生日 = forms.DateTimeField(required=False)
    验证码 = CaptchaField()
    class Meta:
        model = User
        fields = ('username','password1','password2','email','昵称','生日')



class Custom_Table2(UserChangeForm):
    昵称 = forms.CharField(max_length=50,required=False)
    生日 = forms.DateTimeField(required=False)

    class Meta:
        model = User
        fields = ('username','password','email','昵称','生日')

class Custom_Table3(AuthenticationForm):
    验证码 = CaptchaField()

myapp/views.py
from django.shortcuts import render,redirect
from myapp.models import Doubans,Biancheng,Keji
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm
from .forms import Custom_Table,Custom_Table2,Custom_Table3
from .models import Ordinarymember
# Create your views here.
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
def start(request):

  return render(request,'myapp/start.html',{"title":"爬虫图书搜索系统"})

def base(request):

  return render(request,'myapp/base.html')

def home(request):

  return render(request,'myapp/home.html',{"title":"爬虫图书搜索系统"})

def tuijian(request,index=1):
  list = Doubans.objects.all()

  paginator = Paginator(list, 6)
  # 得到当前的页面数据
  page = paginator.page(index)

  # 获取当前页面数，这里是传过来的index
  currentPage = int(index)

  # 下面这段逻辑是保证标签始终是10个，所选的标签在中间
  if currentPage < 5:
    pageRange = range(1, 11)
  elif currentPage > paginator.num_pages - 6:
    pageRange = range(paginator.num_pages - 8, paginator.num_pages + 2)
  else:
    pageRange = range(currentPage - 4, currentPage + 6)
  # 将数据封装传到模板中
  context = {'page': page, 'pageRange': pageRange,'title':'通信书类',}

  return render(request,'myapp/tuijian.html',context)

def mine(request,index=1):

  list = Keji.objects.all()

  paginator = Paginator(list, 6)
  # 得到当前的页面数据
  page = paginator.page(index)

  # 获取当前页面数，这里是传过来的index
  currentPage = int(index)

  # 下面这段逻辑是保证标签始终是10个，所选的标签在中间
  if currentPage < 5:
    pageRange = range(1, 11)
  elif currentPage > paginator.num_pages - 6:
    pageRange = range(paginator.num_pages - 8, paginator.num_pages + 2)
  else:
    pageRange = range(currentPage - 4, currentPage + 6)
  # 将数据封装传到模板中
  context = {'page': page, 'pageRange': pageRange,'title':'科技书类',}
  return render(request,'myapp/mine.html',context)


def lianxi(request):

  return render(request,'myapp/lianxi.html',{"title":"联系我们"})

def like(request,index=1):
  list = Biancheng.objects.all()

  paginator = Paginator(list, 6)
  # 得到当前的页面数据
  page = paginator.page(index)

  # 获取当前页面数，这里是传过来的index
  currentPage = int(index)

  # 下面这段逻辑是保证标签始终是10个，所选的标签在中间
  if currentPage < 5:
    pageRange = range(1, 11)
  elif currentPage > paginator.num_pages - 6:
    pageRange = range(paginator.num_pages - 8, paginator.num_pages + 2)
  else:
    pageRange = range(currentPage - 4, currentPage + 6)
  # 将数据封装传到模板中
  context = {'page': page, 'pageRange': pageRange,'title':'编程书类',}

  return render(request,'myapp/like.html',context)

def login1(request):
  if request.method == 'POST':
      login_table = Custom_Table3(data = request.POST)
      if login_table.is_valid():
        user = authenticate(request,username= login_table.cleaned_data['username'],password=login_table.cleaned_data['password'])
        login(request, user)
        return redirect('myapp:home')

  else:
     login_table = Custom_Table3()
     content = {'login_table':login_table, 'user': request.user}

     return render(request, 'myapp/login.html', content)


def loginout(request):
       logout(request)
       return redirect('myapp:home')

def register(request):
  if  request.method == 'POST':
      registerform = Custom_Table(request.POST)
      if registerform.is_valid():
          registerform.save()
          user = authenticate(username=registerform.cleaned_data['username'], password=registerform.cleaned_data['password1'])
          user.email = registerform.cleaned_data['email']
          Ordinarymember(用户=user,昵称=registerform.cleaned_data['昵称'],生日=registerform.cleaned_data['生日']).save()
          login(request, user)
          return redirect('myapp:home')
  else:

    registerform = Custom_Table()
  content = {'registerform':registerform,"title":"注册"}
  return render(request,'myapp/register.html',content)


@login_required(login_url='myapp:login')
def user_center(request):
    content = { 'user':request.user}
    return render(request,'myapp/user_center.html',content)

@login_required(login_url='myapp:login')
def edit_profile(request):
    if request.method == 'POST':
        Edit_Form = Custom_Table2(request.POST,instance=request.user)
        if Edit_Form.is_valid():
            Edit_Form.save()
            request.user.ordinarymember.昵称 = Edit_Form.cleaned_data['昵称']
            request.user.ordinarymember.生日= Edit_Form.cleaned_data['生日']
            request.user.ordinarymember.save()
             #Ordinarymember(用户=user, 昵称=registerform.cleaned_data['昵称'], 生日=registerform.cleaned_data['生日']).save()

            return redirect('myapp:home')
    else:

        Edit_Form = Custom_Table2(instance=request.user)
    content = {'Edit_Form': Edit_Form,'user':request.user}

    return render(request,'myapp/edit_profile.html',content)
@login_required(login_url='myapp:login')
def change_password(request):

    if request.method == 'POST':
        Secret_Form = PasswordChangeForm(data=request.POST,user=request.user)
        if Secret_Form.is_valid():
            Secret_Form.save()
            return redirect('myapp:login')

    else:

        Secret_Form = PasswordChangeForm(user=request.user)
    content = {'Secret_Form': Secret_Form,'user':request.user}

    return render(request,'myapp/change_password.html',content)

templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
     <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,minimum-scale=1.0,user-scalable=0" />
    {#    导入通用css  #}
    <link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css">
    <link rel="stylesheet" href="../../static/main/css/reset.css">
    <link rel="stylesheet" href="../../static/main/css/base.css">




    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/Swiper/3.4.2/js/swiper.js"></script>
    <script src="../../static/main/js/base.js"></script>
    {% block linkscript%}

    {% endblock linkscript%}



    <link rel="icon" href="../../static/main/img/favicon.ico" type="image/x-icon"/>

</head>
<body>
       <header>
       <div class=" daohang navbar navbar-default navbar-fixed-top">
           <div class="container">
           <div class="navbar-header">
               <a href="/home/" class="navbar-brand">爬虫图书搜索系统</a>
           </div>

               <ul class="nav navbar-nav navbar-right ">
                   {% if user.is_authenticated %}
                    <li><a href="{% url 'myapp:loginout' %}">登出</a></li>
                    <li><a href="{% url 'myapp:user_center' %}">个人中心</a></li>
                   {% else %}
                    <li><a href="{% url 'myapp:login' %}">登录</a></li>
                    <li><a href="/register/">注册</a></li>
                   {% endif %}

               </ul>
           </div>
           </div>
            <div class="container">
           <div class=" row search ">
               <div class="col-sm-4 ">
                  <p class="search1">图书搜索</p>
               </div>
               <div class="col-sm-5 ">
                   <form action="{% url 'haystack_search' %}" method="get" name="q" target="_blank">
                   <div class="input-group input-group-lg"  >

                       <input type="search" class="form-control" name="q" placeholder="书名、作者、出版社">

                       <span class="input-group-btn">
                       <button class="btn btn-primary" type="submit">搜索</button>
                       </span>

                   </div>
                   </form>
               </div>
           </div>
            </div>







       </header>

      <div>
          <div class="container" >
              <div class="row" >
                  <div class="col-sm-3 " >
                      <p class="type">分类</p>

                  <div class="list-group  side-bar " >

                      <a href="/home/" class="list-group-item  " >热门图书</a>
                      <a href="/tuijian/" class=" list-group-item  " >通信书类</a>
                     <a href="/like/" class="list-group-item " >编程书类</a>
                      <a href="/mine/" class="list-group-item" >科技书类</a>
                      <a href="/lianxi/" class="list-group-item" >联系我们</a>

                  </div>
                      <p class="type">标签</p>
                      <div class="biaoqian">
                          <span class="label label-default">历史</span>
                          <span class="label label-primary">童话</span>
                          <span class="label label-success">散文</span>
                          <span class="label label-info">诗歌</span>
                          <span class="label label-default">职场</span>
                          <span class="label label-warning">古典文学</span>
                          <span class="label label-danger">军事</span>
                          <span class="label label-primary">电影</span>
                          <span class="label label-warning">言情</span>
                          <span class="label label-success">互联网</span>
                          <span class="label label-info">金融</span>
                          <span class="label label-primary">广告</span>
                          <span class="label label-warning">科技</span>
                          <span class="label label-success">武侠</span>
                          <span class="label label-info">推理</span>
                          <span class="label label-default">言情</span>
                          <span class="label label-warning">穿越</span>
                          <span class="label label-danger">教育</span>
                          <span class="label label-primary">回忆录</span>
                      </div>

                      <div class="row ">
                          <a class="col-sm-5" href="https://m.douban.com/time/column/123/?dt_time_source=douban-web_inner_right" target="_blank"><img src="../../static/main/img/01def764b59163a.jpg"  style="width: 100px;margin-top: 20px;height: 100px"></a>
                          <p class="col-sm-7" style="margin-top: 20px">
                              <a class="kecheng" href="https://m.douban.com/time/column/123/?dt_time_source=douban-web_inner_right" target="_blank" >豆瓣时间 | 提升沟通力，专治各种说不通</a>
                          </p>
                      </div>
                      <p style="margin-top: 50px;padding-bottom:10px;font-size: 23px;border-bottom:5px solid #cd0009;">网上有害信息举报专区</p>
                      <a href="http://report.12377.cn:13225/toreportinputNormal_anis.do" target="_blank" ><img src="../../static/home/img/youhaixxjb.jpg"
                           style="width: 261px;margin-top: 20px;height: 200px"></a>



                      <a href="https://www.douban.com/gallery/topic/39566/?utm_source=douban&utm_medium=Display_Directbanner&utm_campaign=holidaycampaign_201812_02" target="_blank"><img src="../../static/main/img/3898eba705ad55b.jpg"  style="width: 261px;margin-top: 20px;height: 300px"></a>

                      <div style="line-height: 1; text-align: center; background-color: rgba(0, 0, 0, 0.3); font-size: 12px; position: absolute; right: 17px; bottom: 0; padding: 4px; color: rgb(255, 255, 255);">广告</div>
                   </div>





                  {% block base %}
                  {% endblock base %}

              </div>
          </div>
      </div>

   <!-- <footer>
        <div class="footer1">
            @ 2018 爬虫图书 中国互联网举报中心京ICP证1401号京ICP备125439号-3京公安备
        </div>
-->
    </footer>

</body>
</html>

templates/myapp/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码</title>
    <link rel="icon" href="../../static/main/img/favicon.ico" type="image/x-icon"/>
</head>
<body>
<h1>修改密码</h1>
<a href="{% url 'myapp:home' %}">回到主页</a>
   <a href="{% url 'myapp:user_center' %}">个人中心</a>
   <a href="{% url 'myapp:edit_profile' %}">编辑个人信息</a>
   <a href="{% url 'myapp:change_password' %}">修改密码</a>
   <a href="{% url 'myapp:loginout' %}">登出</a>
    <form action="" method="post">
        {% csrf_token %}
        {{ Secret_Form.as_p }}
    <button type="submit">确认修改</button>
    </form>


</body>
</html>

templates/myapp/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑个人信息</title>
    <link rel="icon" href="../../static/main/img/favicon.ico" type="image/x-icon"/>
</head>
<body>
<h1>编辑个人信息</h1>
<a href="{% url 'myapp:home' %}">回到主页</a>
   <a href="{% url 'myapp:user_center' %}">个人中心</a>
   <a href="{% url 'myapp:edit_profile' %}">编辑个人信息</a>
   <a href="{% url 'myapp:change_password' %}">修改密码</a>
   <a href="{% url 'myapp:loginout' %}">登出</a>
    <form action="" method="post">
        {% csrf_token %}


        <p><label for="id_username">用户名:</label> <input type="text" name="username" value="{{ user.username }}" maxlength="150" required id="id_username" /> </p>

        <p><label for="id_email">电子邮件地址:</label> <input type="email" name="email" value="{{ user.email }}" maxlength="254" id="id_email" /></p>
        <p><label for="id_昵称">昵称:</label> <input type="text" name="昵称" maxlength="50" id="id_昵称" value="  {{ user.ordinarymember.昵称 }}"/></p>
        <p><label for="id_生日">生日:</label> <input type="date" name="生日" id="id_生日" value=" {{ user.ordinarymember.生日 }}"/></p>
    <button type="submit">确认修改</button>
    </form>


</body>
</html>

templates/myapp/lianxi.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>



    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,minimum-scale=1.0,user-scalable=0" />
    {#    导入通用css  #}
    <link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css">
    <link rel="stylesheet" href="../../static/main/css/reset.css">
    <link rel="stylesheet" href="../../static/main/css/base.css">



    <script src="../../static/main/js/base.js"></script>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/Swiper/3.4.2/js/swiper.js"></script>


    <link rel="stylesheet" href="../../static/lianxi/lianxi.css">

   <link rel="icon" href="../../static/main/img/favicon.ico" type="image/x-icon"/>
</head>
<body>
<header>
    <div class=" daohang navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a href="/home/" class="navbar-brand">爬虫图书搜索系统</a>
            </div>

            <ul class="nav navbar-nav navbar-right ">
                <li><a href="/login/">登录</a></li>
                <li><a href="/register/">注册</a></li>
            </ul>
        </div>
    </div>
    <div class="container">
        <div class=" row search ">
            <div class="col-sm-4 ">
                <p class="search1">图书搜索</p>
            </div>
            <div class="col-sm-5 ">
                <div class="input-group input-group-lg">
                    <input type="text" class="form-control" placeholder="书名、作者、出版社">
                    <span class="input-group-btn">
        <button class="btn btn-primary" type="button">搜索</button>
        </span>
                </div>
            </div>
        </div>
    </div>







</header>

<div>
    <div class="container" >
        <div class="row" >
            <div class="col-sm-3" >
                <p class="type">分类</p>

                <div class="list-group  side-bar " >

                    <a  href="/home/" class="list-group-item "   >热门图书</a>
                    <a href="/tuijian/" class=" list-group-item  " >通信书类</a>
                    <a href="/like/" class="list-group-item " >编程书类</a>
                    <a href="/mine/" class="list-group-item" >科技书类</a>
                    <a href="/lianxi/" class="list-group-item active" >联系我们</a>
                </div>
                <p class="type">标签</p>
                <div class="biaoqian">
                    <span class="label label-default">历史</span>
                    <span class="label label-primary">童话</span>
                    <span class="label label-success">散文</span>
                    <span class="label label-info">诗歌</span>
                    <span class="label label-default">职场</span>
                    <span class="label label-warning">古典文学</span>
                    <span class="label label-danger">军事</span>
                    <span class="label label-primary">电影</span>
                    <span class="label label-warning">言情</span>
                    <span class="label label-success">互联网</span>
                    <span class="label label-info">金融</span>
                    <span class="label label-primary">广告</span>
                    <span class="label label-warning">科技</span>
                    <span class="label label-success">武侠</span>
                    <span class="label label-info">推理</span>
                    <span class="label label-default">言情</span>
                    <span class="label label-warning">穿越</span>
                    <span class="label label-danger">教育</span>
                    <span class="label label-primary">回忆录</span>
                </div>

                <div class="row ">
                    <a class="col-sm-5" href="https://m.douban.com/time/column/123/?dt_time_source=douban-web_inner_right" target="_blank"><img src="../../static/main/img/01def764b59163a.jpg"  style="width: 100px;margin-top: 20px;height: 100px"></a>
                    <p class="col-sm-7" style="margin-top: 20px">
                        <a class="kecheng" href="https://m.douban.com/time/column/123/?dt_time_source=douban-web_inner_right" target="_blank" >豆瓣时间 | 提升沟通力，专治各种说不通</a>
                    </p>
                </div>

            </div>

            <div class="col-sm-9 address">
                <div>联系电话：<a>18179174337</a></div>

                <div>联系地址：<a>xxxxxxxxxxxxxxxxxxxxx</a></div>


            </div>





        </div>



    </div>
  </div>
<!--
<div class="footer1">
    @ 2018 爬虫图书 中国互联网举报中心京ICP证1401号京ICP备125439号-3京公安备
</div>
-->


  </body>
</html>

templates/myapp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>


    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,minimum-scale=1.0,user-scalable=0" />
    {#    导入通用css  #}
    <link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css">
    <link rel="stylesheet" href="../../static/main/css/reset.css">
    <link rel="stylesheet" href="../../static/main/css/base.css">



    <script src="../../static/main/js/base.js"></script>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/Swiper/3.4.2/js/swiper.js"></script>

    <link rel="stylesheet" href="../../static/register/register.css">

   <link rel="icon" href="../../static/main/img/favicon.ico" type="image/x-icon"/>
</head>
<body>

<div class=" daohang navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a href="/home/" class="navbar-brand">图书爬虫搜索系统</a>
        </div>

        <ul class="nav navbar-nav navbar-right ">
            <li><a href="/login/" >登录</a></li>
            <li><a href="/register/">注册</a></li>
        </ul>
    </div>
</div>

<div class="container container-small  " >
    <h1 style="color: #337ab7">注册</h1>




    <form action="" method="post">

        {% csrf_token %}

        <p><label  for="id_username">用户名:</label> <input type="text" class="form-control"  name="username" maxlength="150" autofocus required
                                                        id="id_username"/> <ul><li class="helptext">最多10个字符。包含字母，数字和仅有的@/./+/-/_符号。</li></ul>
        </p>
        {% if registerform.errors.username %}
        <span>  <p>用户名已存在或格式不符合要求</p></span>
             {% endif %}

          <p><label for="id_昵称">昵称:</label> <input class="form-control" type="text" name="昵称" maxlength="50" id="id_昵称"/></p>
        <span>{{ registerform.errors.昵称 }}</span>
        <p><label for="id_password1">密码:</label> <input  class="form-control" type="password" name="password1" required id="id_password1"/>
           <ul class="helptext"><li>你的密码不能与其他个人信息太相似。</li><li>你的密码必须包含至少 8 个字符。</li><li>你的密码不能是大家都爱用的常见密码。</li><li>你的密码不能全部为数字。</li></ul>
        </p>
         {% if registerform.errors.password1 %}
        <span><p>密码不符合要求</p></span>
         {% endif %}
        <p><label for="id_password2">密码确认:</label> <input class="form-control" type="password" name="password2" required id="id_password2"/>
           <ul> <li class="helptext">为了校验，请输入与上面相同的密码。</li></ul></p>
        <span>{{ registerform.errors.password2 }}</span>
        <p><label for="id_email">电子邮件地址:</label> <input  class="form-control" type="email" name="email" maxlength="254" id="id_email"/></p>
        <span>{{ registerform.errors.email }}</span>

        <p><label for="id_生日">生日:</label> <input  class="form-control" type="date" name="生日" id="id_生日"/></p>
        <span>{{ registerform.errors.生日 }}</span>
        <p ><label>请输入验证码:</label>{{ registerform.验证码 }}</p>
           {% if registerform.errors.验证码 %}
             <span><p>验证码错误</p></span>
            {% endif %}


        <!--<label>用户名/手机/邮箱</label>-->

            <!--<input type="text" class="form-control">-->



        <div class="form-group">
           注册即代表您同意<<a href="#">此系统服务条款</a>>
        </div>

        <div class="form-group last">
            <button type="submit" class="btn btn-primary btn-block">注册</button>
        </div>
    </form>





</div>
<!--<div class="footer">
    @ 2018 爬虫图书 中国互联网举报中心京ICP证1401号京ICP备125439号-3京公安备
</div>-->

</body>
</html>

templates/myapp/user_center.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人中心</title>
    <link rel="icon" href="../../static/main/img/favicon.ico" type="image/x-icon"/>
</head>
<body>
<h1 >个人中心</h1>
   <a href="{% url 'myapp:home' %}">回到主页</a>
   <a href="{% url 'myapp:edit_profile' %}">编辑个人信息</a>
   <a href="{% url 'myapp:change_password' %}">修改密码</a>
   <a href="{% url 'myapp:loginout' %}">登出</a>
   <div>
       <p>用户名：{{user.username }}</p>
       <p>电子邮箱： {{user.email }}</p>
       <p>昵称：{{user.ordinarymember.昵称}}</p>
       <p>生日： {{user.ordinarymember.生日 }}</p>
   </div>
</body>
</html>